/users/basbas/eclipse/plugins/lpg.generator_2.0.18/include/java/KWLexerFoldedCaseMapF.gi:19:24:19:24:492:492: Warning: The macro "$" is undefined. No substitution made
/users/basbas/eclipse/plugins/lpg.generator_2.0.18/include/java/KWLexerFoldedCaseMapF.gi:2:5:2:14:16:25: Informative: The terminal DollarSign is useless.
/users/basbas/eclipse/plugins/lpg.generator_2.0.18/include/java/KWLexerFoldedCaseMapF.gi:3:5:3:11:39:45: Informative: The terminal Percent is useless.
/users/basbas/eclipse/plugins/lpg.generator_2.0.18/include/java/KWLexerFoldedCaseMapF.gi:5:23:5:23:83:83: Informative: The terminal j is useless.
/users/basbas/eclipse/plugins/lpg.generator_2.0.18/include/java/KWLexerFoldedCaseMapF.gi:5:25:5:25:85:85: Informative: The terminal k is useless.
/users/basbas/eclipse/plugins/lpg.generator_2.0.18/include/java/KWLexerFoldedCaseMapF.gi:5:55:5:55:115:115: Informative: The terminal z is useless.


