package sial.parser;

public interface SialParsersym {
    public final static int
      TK_COMMA = 6,
      TK_PLUS = 3,
      TK_MINUS = 2,
      TK_STAR = 44,
      TK_SLASH = 48,
      TK_TENSOR = 49,
      TK_GREATER = 75,
      TK_GEQ = 76,
      TK_LESS = 77,
      TK_LEQ = 78,
      TK_EQ = 79,
      TK_NEQ = 80,
      TK_ASSIGN = 42,
      TK_PLUS_ASSIGN = 54,
      TK_MINUS_ASSIGN = 55,
      TK_STAR_ASSIGN = 56,
      TK_LEFTPAREN = 50,
      TK_RIGHTPAREN = 51,
      TK_LEFTSQUARE = 5,
      TK_RIGHTSQUARE = 40,
      TK_COLON = 57,
      TK_EXP = 45,
      TK_sial = 81,
      TK_endsial = 82,
      TK_proc = 83,
      TK_endproc = 84,
      TK_return = 7,
      TK_call = 8,
      TK_pardo = 9,
      TK_endpardo = 85,
      TK_do = 10,
      TK_in = 58,
      TK_enddo = 59,
      TK_cycle = 95,
      TK_exit = 11,
      TK_if = 12,
      TK_else = 86,
      TK_endif = 60,
      TK_put = 13,
      TK_get = 14,
      TK_prepare = 15,
      TK_request = 16,
      TK_prequest = 96,
      TK_collective = 17,
      TK_execute = 18,
      TK_aoindex = 61,
      TK_moindex = 62,
      TK_moaindex = 63,
      TK_mobindex = 64,
      TK_index = 65,
      TK_laindex = 66,
      TK_subindex = 87,
      TK_of = 88,
      TK_scalar = 52,
      TK_int = 53,
      TK_static = 67,
      TK_temp = 68,
      TK_local = 69,
      TK_distributed = 70,
      TK_served = 71,
      TK_create = 19,
      TK_delete = 20,
      TK_allocate = 21,
      TK_deallocate = 22,
      TK_destroy = 23,
      TK_where = 89,
      TK_import = 90,
      TK_predefined = 72,
      TK_special = 91,
      TK_server_barrier = 24,
      TK_sip_barrier = 25,
      TK_section = 26,
      TK_endsection = 92,
      TK_print = 27,
      TK_println = 28,
      TK_print_index = 97,
      TK_print_scalar = 98,
      TK_print_int = 99,
      TK_contiguous = 46,
      TK_gpu_on = 29,
      TK_gpu_off = 93,
      TK_gpu_allocate = 30,
      TK_gpu_free = 31,
      TK_gpu_put = 32,
      TK_gpu_get = 33,
      TK_set_persistent = 34,
      TK_restore_persistent = 35,
      TK_sparse = 73,
      TK_assert_same = 36,
      TK_broadcast_from = 37,
      TK_sqrt = 74,
      TK_stop = 38,
      TK_EOF_TOKEN = 94,
      TK_SINGLE_LINE_COMMENT = 47,
      TK_IDENTIFIER = 1,
      TK_INTLIT = 39,
      TK_DOUBLELIT = 41,
      TK_EOL = 4,
      TK_STRINGLIT = 43,
      TK_ERROR_TOKEN = 100;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "IDENTIFIER",
                 "MINUS",
                 "PLUS",
                 "EOL",
                 "LEFTSQUARE",
                 "COMMA",
                 "return",
                 "call",
                 "pardo",
                 "do",
                 "exit",
                 "if",
                 "put",
                 "get",
                 "prepare",
                 "request",
                 "collective",
                 "execute",
                 "create",
                 "delete",
                 "allocate",
                 "deallocate",
                 "destroy",
                 "server_barrier",
                 "sip_barrier",
                 "section",
                 "print",
                 "println",
                 "gpu_on",
                 "gpu_allocate",
                 "gpu_free",
                 "gpu_put",
                 "gpu_get",
                 "set_persistent",
                 "restore_persistent",
                 "assert_same",
                 "broadcast_from",
                 "stop",
                 "INTLIT",
                 "RIGHTSQUARE",
                 "DOUBLELIT",
                 "ASSIGN",
                 "STRINGLIT",
                 "STAR",
                 "EXP",
                 "contiguous",
                 "SINGLE_LINE_COMMENT",
                 "SLASH",
                 "TENSOR",
                 "LEFTPAREN",
                 "RIGHTPAREN",
                 "scalar",
                 "int",
                 "PLUS_ASSIGN",
                 "MINUS_ASSIGN",
                 "STAR_ASSIGN",
                 "COLON",
                 "in",
                 "enddo",
                 "endif",
                 "aoindex",
                 "moindex",
                 "moaindex",
                 "mobindex",
                 "index",
                 "laindex",
                 "static",
                 "temp",
                 "local",
                 "distributed",
                 "served",
                 "predefined",
                 "sparse",
                 "sqrt",
                 "GREATER",
                 "GEQ",
                 "LESS",
                 "LEQ",
                 "EQ",
                 "NEQ",
                 "sial",
                 "endsial",
                 "proc",
                 "endproc",
                 "endpardo",
                 "else",
                 "subindex",
                 "of",
                 "where",
                 "import",
                 "special",
                 "endsection",
                 "gpu_off",
                 "EOF_TOKEN",
                 "cycle",
                 "prequest",
                 "print_index",
                 "print_scalar",
                 "print_int",
                 "ERROR_TOKEN"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
